### ISSUE TITLE
[Polish programtv.onet.pl] Some channels have totally different EPG than the website.

### ISSUE THREAD

**Issue by monoik** [iptv-org/epg#398]
Some (not all) channels currently have totally different EPG in the XML than the website

Some sample ones which are currently incorrect:

Canal+ Domo
Kino Polska
TVN

The timestamps in the xml file indicate the current date and time for the incorrect programs.
Searching the website for the programs doesn't net any results. For example:
`<programme start="20220116093500 +0000" stop="20220116103000 +0000" channel="CanalPlusDomo.pl"><title lang="pl">Ucieczka na wieś 19, odc. 5</title><desc lang="pl">...</desc><category lang="pl">serial dokumentalny</category></programme>
`
Searching for "Ucieczka na wieś 19, odc. 5" only finds "Ucieczka na wieś 19, odc. 25" which is not the same programme.

The programmes seem to be from the correct channel, just from different day perhaps?

Another thing, perhaps connected: EPG data is missing for TVN Style, but it's back tomorrow at 3 AM.

**Comment by monoik** [comment]
The problematic channels seem to have yesterday's EPG as today.

**Comment by freearhey** [comment]
Fixed in #399

**Comment by monoik** [comment]
Hi freearhey, unfortunately the issue is not fixed. Today the EPG for TVN is again from yesterday. There must be a more complicated underlying problem which simply taking next day's EPG didn't fix...

**Comment by freearhey** [comment]
Please check again.
